### PR TITLE
Ensure NULL-able Enums don't raise peewee.IntegrityError.

### PR DESCRIPTION
**Pull request by echernyavskiy**

### CODE REVIEW

**Comment by enpaul** [comment]
Can you run the command `black peewee_plus.py` and squash the changes into the commit? I can merge this once that's done.

**Comment by echernyavskiy** [comment]
> Can you run the command `black peewee_plus.py` and squash the changes into the commit? I can merge this once that's done.

yup, done

**Comment by echernyavskiy** [comment]
Looks like `safety` found an insecure package. @enpaul could you update pyproject.toml so that checks succeed on both `master` and this feature branch?

**Comment by enpaul** [comment]
@echernyavskiy The CI issue should be fixed now. If you rebase off of the `devel` branch it should pass

**Review by enpaul — APPROVED** [review]

**Comment by echernyavskiy** [comment]
> @echernyavskiy The CI issue should be fixed now. If you rebase off of the `devel` branch it should pass

Done, and all checks have passed.

**Comment by echernyavskiy** [comment]
@enpaul could you cut a release please?

**Pull request merged**
